version: "3"

services:
  email_service:
    container_name: email_service
    build: .
    ports:
      - "8085:8085"
    environment:
      - PORT=8085
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM=${SMTP_FROM}
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    env_file:
      - .env
    # depends_on:
    #   - rabbitmq
    restart: unless-stopped

  # rabbitmq:
  #   container_name: rabbitmq_email
  #   image: rabbitmq:3-management
  #   ports:
  #     - "5672:5672"  # AMQP port
  #     - "15672:15672"  # Management UI
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=guest
  #     - RABBITMQ_DEFAULT_PASS=guest
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq
  #   restart: unless-stopped

volumes:
  rabbitmq_data:
