// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Invoice struct {
	InvoiceID                  uuid.UUID      `json:"invoice_id"`
	InvoiceNumber              string         `json:"invoice_number"`
	InvoiceType                sql.NullString `json:"invoice_type"`
	CustomerID                 string         `json:"customer_id"`
	TicketID                   string         `json:"ticket_id"`
	TotalAmount                float64        `json:"total_amount"`
	DiscountAmount             sql.NullString `json:"discount_amount"`
	TaxAmount                  sql.NullString `json:"tax_amount"`
	FinalAmount                float64        `json:"final_amount"`
	Currency                   sql.NullString `json:"currency"`
	PaymentStatus              sql.NullString `json:"payment_status"`
	PaymentMethod              sql.NullString `json:"payment_method"`
	IssueDate                  sql.NullTime   `json:"issue_date"`
	Notes                      string         `json:"notes"`
	CreatedAt                  sql.NullTime   `json:"created_at"`
	UpdatedAt                  sql.NullTime   `json:"updated_at"`
	VnpayTxnRef                sql.NullString `json:"vnpay_txn_ref"`
	VnpayBankCode              sql.NullString `json:"vnpay_bank_code"`
	VnpayTxnNo                 sql.NullString `json:"vnpay_txn_no"`
	VnpayPayDate               sql.NullString `json:"vnpay_pay_date"`
	StripePaymentIntentID      sql.NullString `json:"stripe_payment_intent_id"`
	StripeChargeID             sql.NullString `json:"stripe_charge_id"`
	StripeCustomerID           sql.NullString `json:"stripe_customer_id"`
	StripePaymentMethodDetails string         `json:"stripe_payment_method_details"`
	BankTransferCode           sql.NullString `json:"bank_transfer_code"`
	BankAccountName            sql.NullString `json:"bank_account_name"`
	BankAccountNumber          sql.NullString `json:"bank_account_number"`
	BankName                   sql.NullString `json:"bank_name"`
	BankTransactionID          sql.NullString `json:"bank_transaction_id"`
	BankPaymentDetails         string         `json:"bank_payment_details"`
}
