// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	GetInvoiceByBankTransferCode(ctx context.Context, bankTransferCode sql.NullString) (Invoice, error)
	GetInvoiceByID(ctx context.Context, invoiceID uuid.UUID) (Invoice, error)
	GetInvoiceByStripePaymentIntentID(ctx context.Context, stripePaymentIntentID sql.NullString) (Invoice, error)
	GetInvoiceByVNPayTxnRef(ctx context.Context, vnpayTxnRef sql.NullString) (Invoice, error)
	GetLatestCompletedInvoiceByTicketID(ctx context.Context, ticketID string) (Invoice, error)
	ListInvoicesByCustomerID(ctx context.Context, customerID string) ([]Invoice, error)
	// Used when an admin/system confirms a bank payment
	UpdateInvoiceBankPaymentConfirmation(ctx context.Context, arg UpdateInvoiceBankPaymentConfirmationParams) (Invoice, error)
	// Used when creating a bank payment request (invoice is PENDING or AWAITING_CONFIRMATION)
	UpdateInvoiceBankPaymentRequest(ctx context.Context, arg UpdateInvoiceBankPaymentRequestParams) (Invoice, error)
	// Update status when payment fails (generic for Stripe, VNPay, or Bank based on invoice_id)
	UpdateInvoicePaymentFailed(ctx context.Context, arg UpdateInvoicePaymentFailedParams) (Invoice, error)
	// Update general status (e.g., REFUNDED, CANCELED)
	UpdateInvoiceStatusGeneral(ctx context.Context, arg UpdateInvoiceStatusGeneralParams) (Invoice, error)
	// Used when creating Payment Intent and need to update invoice with PI ID
	UpdateInvoiceStripePaymentIntent(ctx context.Context, arg UpdateInvoiceStripePaymentIntentParams) (Invoice, error)
	UpdateInvoiceStripePaymentSuccess(ctx context.Context, arg UpdateInvoiceStripePaymentSuccessParams) (Invoice, error)
	UpdateInvoiceVNPayStatus(ctx context.Context, arg UpdateInvoiceVNPayStatusParams) (Invoice, error)
}

var _ Querier = (*Queries)(nil)
