version: '3'

services:
  qr_service:
    container_name: qr_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    restart: unless-stopped

volumes:
  postgres_qr_data:
