version: '3'

services:
  noti_service:
    container_name: noti_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    # depends_on:
    #   - postgres_noti
    env_file:
      - .env
    # environment:
    #   - DB_HOST=postgres_noti
    #   - DB_PORT=5437
    restart: unless-stopped

  # postgres_noti:
  #   container_name: postgres_noti
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_NAME}
  #   ports:
  #     - "${DB_PORT}:5437"
  #   command: -p 5437
  #   volumes:
  #     - postgres_noti_data:/var/lib/postgresql/data
  #     - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_noti_data:
