version: "3.8"

services:
  rasa:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1

  action_server:
    build:
      context: .
      dockerfile: Dockerfile.actions
    ports:
      - "5055:5055"
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
