// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Invoice struct {
	ID         int32     `json:"id"`
	ShipmentID int32     `json:"shipment_id"`
	Amount     float64   `json:"amount"`
	IssuedAt   time.Time `json:"issued_at"`
	CreatedAt  time.Time `json:"created_at"`
}

type Shipment struct {
	ID           int32     `json:"id"`
	TripID       int32     `json:"trip_id"`
	SenderName   string    `json:"sender_name"`
	ReceiverName string    `json:"receiver_name"`
	ItemName     string    `json:"item_name"`
	ItemType     string    `json:"item_type"`
	Weight       float64   `json:"weight"`
	Length       float64   `json:"length"`
	Width        float64   `json:"width"`
	Height       float64   `json:"height"`
	Volume       float64   `json:"volume"`
	Price        float64   `json:"price"`
	PayerType    string    `json:"payer_type"`
	Note         string    `json:"note"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
