// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	CreateShipment(ctx context.Context, arg CreateShipmentParams) (Shipment, error)
	GetInvoiceByID(ctx context.Context, id int32) (Invoice, error)
	GetInvoiceByShipmentID(ctx context.Context, shipmentID int32) (Invoice, error)
	GetShipmentByID(ctx context.Context, id int32) (Shipment, error)
	ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]Invoice, error)
	ListInvoicesByTripID(ctx context.Context, tripID int32) ([]Invoice, error)
	ListShipments(ctx context.Context, arg ListShipmentsParams) ([]Shipment, error)
	ListShipmentsByTripID(ctx context.Context, tripID int32) ([]Shipment, error)
}

var _ Querier = (*Queries)(nil)
