// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

// Stores FCM device tokens for users
type FcmToken struct {
	UserID    string    `json:"user_id"`
	Token     string    `json:"token"`
	CreatedAt time.Time `json:"created_at"`
}

type Notification struct {
	ID pgtype.UUID `json:"id"`
	// NULL for broadcast messages, user identifier for specific messages
	UserID    pgtype.Text `json:"user_id"`
	Type      string      `json:"type"`
	Title     string      `json:"title"`
	Message   string      `json:"message"`
	IsRead    pgtype.Bool `json:"is_read"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}
