// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountNews(ctx context.Context) (int64, error)
	CreateNews(ctx context.Context, arg CreateNewsParams) (News, error)
	DeleteNews(ctx context.Context, id uuid.UUID) error
	GetNewsByID(ctx context.Context, id uuid.UUID) (News, error)
	ListNews(ctx context.Context, arg ListNewsParams) ([]News, error)
	UpdateNews(ctx context.Context, arg UpdateNewsParams) (News, error)
}

var _ Querier = (*Queries)(nil)
