// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Checkin struct {
	ID           int32          `json:"id"`
	SeatTicketID int32          `json:"seat_ticket_id"`
	TicketID     string         `json:"ticket_id"`
	TripID       string         `json:"trip_id"`
	SeatName     sql.NullString `json:"seat_name"`
	CheckedInAt  sql.NullTime   `json:"checked_in_at"`
	Note         string         `json:"note"`
}

type OutboxEvent struct {
	ID        uuid.UUID       `json:"id"`
	Topic     string          `json:"topic"`
	Key       string          `json:"key"`
	Payload   json.RawMessage `json:"payload"`
	CreatedAt time.Time       `json:"created_at"`
}

type Seat struct {
	ID        int32          `json:"id"`
	TripID    string         `json:"trip_id"`
	SeatName  sql.NullString `json:"seat_name"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type SeatTicket struct {
	ID        int32        `json:"id"`
	SeatID    int32        `json:"seat_id"`
	TicketID  string       `json:"ticket_id"`
	Status    int16        `json:"status"`
	TripID    string       `json:"trip_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Ticket struct {
	TicketID       string         `json:"ticket_id"`
	TripIDBegin    string         `json:"trip_id_begin"`
	TripIDEnd      sql.NullString `json:"trip_id_end"`
	Type           int16          `json:"type"`
	CustomerID     sql.NullInt32  `json:"customer_id"`
	Phone          sql.NullString `json:"phone"`
	Email          sql.NullString `json:"email"`
	Name           sql.NullString `json:"name"`
	Price          float64        `json:"price"`
	Status         int16          `json:"status"`
	BookingTime    time.Time      `json:"booking_time"`
	PaymentStatus  int16          `json:"payment_status"`
	BookingChannel int16          `json:"booking_channel"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	PolicyID       int32          `json:"policy_id"`
	BookedBy       sql.NullString `json:"booked_by"`
}

type TicketDetail struct {
	DetailID             int32         `json:"detail_id"`
	TicketID             string        `json:"ticket_id"`
	PickupLocationBegin  sql.NullInt32 `json:"pickup_location_begin"`
	DropoffLocationBegin sql.NullInt32 `json:"dropoff_location_begin"`
	PickupLocationEnd    sql.NullInt32 `json:"pickup_location_end"`
	DropoffLocationEnd   sql.NullInt32 `json:"dropoff_location_end"`
	CreatedAt            time.Time     `json:"created_at"`
	UpdatedAt            time.Time     `json:"updated_at"`
}

type TicketLog struct {
	LogID     int32     `json:"log_id"`
	TicketID  string    `json:"ticket_id"`
	Action    string    `json:"action"`
	CreatedAt time.Time `json:"created_at"`
}
