// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        int64     `json:"id"`
	OwnerName string    `json:"owner_name"`
	Balance   int64     `json:"balance"`
	Currency  string    `json:"currency"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TransactionHistory struct {
	ID              int64          `json:"id"`
	AccountID       int64          `json:"account_id"`
	TransactionType string         `json:"transaction_type"`
	Amount          sql.NullInt64  `json:"amount"`
	Currency        sql.NullString `json:"currency"`
	Description     string         `json:"description"`
	CreatedAt       time.Time      `json:"created_at"`
}
