// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateTransactionHistory(ctx context.Context, arg CreateTransactionHistoryParams) (TransactionHistory, error)
	// Thực tế không xóa, chỉ dùng để minh họa, chúng ta sẽ dùng UpdateAccountStatus
	DeleteAccount(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	// Để tránh deadlock khi cập nhật balance
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListTransactionHistoryByAccountID(ctx context.Context, arg ListTransactionHistoryByAccountIDParams) ([]TransactionHistory, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error)
	UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
