apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service-deployment
  labels:
    app: ticket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      containers:
        - name: ticket-service
          image: duancntt.azurecr.io/ticket-service:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            - name: SERVER_PORT
              value: "8084"
            - name: DATABASE_HOST
              valueFrom:
                {
                  configMapKeyRef:
                    { name: platform-config, key: POSTGRES_HOST },
                }
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              valueFrom:
                {
                  configMapKeyRef:
                    { name: platform-config, key: POSTGRES_USER },
                }
            - name: DATABASE_NAME
              valueFrom:
                {
                  configMapKeyRef:
                    { name: platform-config, key: TICKET_SERVICE_DB_NAME },
                }
            - name: DATABASE_SSL_MODE
              value: "require"
            - name: REDIS_URL
              valueFrom:
                { secretKeyRef: { name: platform-secrets, key: REDIS_URL } }
            - name: QR_SERVICE_URL
              valueFrom:
                {
                  configMapKeyRef:
                    { name: platform-config, key: QR_SERVICE_URL },
                }
            - name: KAFKA_SEEDS
              valueFrom:
                { configMapKeyRef: { name: platform-config, key: KAFKA_SEEDS } }
            - name: KAFKA_ENABLE_TLS
              valueFrom:
                {
                  configMapKeyRef:
                    { name: platform-config, key: KAFKA_ENABLE_TLS },
                }
            - name: DATABASE_PASSWORD
              valueFrom:
                {
                  secretKeyRef:
                    { name: platform-secrets, key: POSTGRES_PASSWORD },
                }
            - name: JWT_TOKEN
              valueFrom:
                {
                  secretKeyRef: { name: platform-secrets, key: JWT_SECRET_KEY },
                }
            - name: KAFKA_SASL_USER
              valueFrom:
                {
                  configMapKeyRef:
                    { name: platform-config, key: KAFKA_SASL_USER },
                }
            - name: KAFKA_SASL_PASS
              valueFrom:
                {
                  secretKeyRef:
                    { name: platform-secrets, key: KAFKA_SASL_PASS },
                }
            - name: KAFKA_TOPIC_TRIP_CREATED
              valueFrom:
                {
                  configMapKeyRef:
                    { name: platform-config, key: KAFKA_TOPIC_TRIP_CREATED },
                }
            - name: KAFKA_GROUP_ID_TRIP_CREATED
              valueFrom:
                {
                  configMapKeyRef:
                    { name: platform-config, key: KAFKA_GROUP_ID_TRIP_CREATED },
                }
            - name: KAFKA_TOPIC_TICKET_STATUS
              valueFrom:
                {
                  configMapKeyRef:
                    { name: platform-config, key: KAFKA_TOPIC_TICKET_STATUS },
                }
            - name: KAFKA_TOPIC_BOOKING_REQUESTS
              valueFrom:
                {
                  configMapKeyRef:
                    {
                      name: platform-config,
                      key: KAFKA_TOPIC_BOOKING_REQUESTS,
                    },
                }
            - name: KAFKA_TOPIC_SEATS_RESERVED
              valueFrom:
                {
                  configMapKeyRef:
                    { name: platform-config, key: KAFKA_TOPIC_SEATS_RESERVED },
                }
            - name: KAFKA_TOPIC_SEATS_RELEASED
              valueFrom:
                {
                  configMapKeyRef:
                    { name: platform-config, key: KAFKA_TOPIC_SEATS_RELEASED },
                }
            - name: KAFKA_TOPIC_EMAIL_REQUESTS
              valueFrom:
                {
                  configMapKeyRef:
                    { name: platform-config, key: KAFKA_TOPIC_EMAIL_REQUESTS },
                }
            - name: KAFKA_TOPIC_QR_REQUESTS
              valueFrom:
                {
                  configMapKeyRef:
                    {
                      name: platform-config,
                      key: KAFKA_TOPIC_ORDER_QR_REQUESTS,
                    },
                }
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-service
spec:
  selector:
    app: ticket-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP
