apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service-deployment
  labels:
    app: email-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
        - name: email-service
          image: duancntt.azurecr.io/email-service:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          env:
            - name: SMTP_SERVER
              value: "smtp.gmail.com"
            - name: SMTP_PORT
              value: "587"
            - name: KAFKA_SEEDS
              valueFrom:
                { configMapKeyRef: { name: platform-config, key: KAFKA_SEEDS } }
            - name: KAFKA_ENABLE_TLS
              valueFrom:
                {
                  configMapKeyRef:
                    { name: platform-config, key: KAFKA_ENABLE_TLS },
                }
            - name: KAFKA_EMAIL_TOPIC
              valueFrom:
                {
                  configMapKeyRef:
                    { name: platform-config, key: KAFKA_TOPIC_EMAIL_REQUESTS },
                }
            - name: KAFKA_GROUP_ID_EMAIL
              valueFrom:
                {
                  configMapKeyRef:
                    { name: platform-config, key: KAFKA_GROUP_ID_EMAIL },
                }
            - name: SMTP_USERNAME
              valueFrom:
                { secretKeyRef: { name: platform-secrets, key: SMTP_USERNAME } }
            - name: SMTP_PASSWORD
              valueFrom:
                { secretKeyRef: { name: platform-secrets, key: SMTP_PASSWORD } }
            - name: SMTP_FROM
              valueFrom:
                { configMapKeyRef: { name: platform-config, key: SMTP_FROM } }
            - name: KAFKA_SASL_USER
              valueFrom:
                {
                  configMapKeyRef:
                    { name: platform-config, key: KAFKA_SASL_USER },
                }
            - name: KAFKA_SASL_PASS
              valueFrom:
                {
                  secretKeyRef: { name: platform-secrets, key: KAFKA_SASL_PASS },
                }
---
apiVersion: v1
kind: Service
metadata:
  name: email-service
spec:
  selector:
    app: email-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP
